### ISSUE TITLE
New NPM package to support grunt 1.0.0

### ISSUE THREAD

**Issue by blacksun1** [csbun/grunt-cmd#3]
Hi,

I see that you have updated the master branch of your component to support Grunt 1.0.0. Thanks very much for that.

Could you please release a new npm package as well so that it can be used?

Thanks in advance,

**Comment by csbun** [comment]
DONE! [https://www.npmjs.com/package/grunt-cmd](https://www.npmjs.com/package/grunt-cmd)

**Comment by blacksun1** [comment]
Super quick!!! Cheers.
